---
- name: Install and configure Nginx
  hosts: 34.171.155.224
  remote_user: devops
  become: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Allow HTTP traffic through UFW
      ufw:
        rule: allow
        name: 'Nginx HTTP'

    - name: Reload UFW
      command: ufw reload
